# Generated by Django 5.2.5 on 2025-09-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('MovieID', models.AutoField(primary_key=True, serialize=False)),
                ('MovieTitle', models.CharField(max_length=200)),
                ('Actor1Name', models.CharField(blank=True, max_length=100)),
                ('Actor2Name', models.CharField(blank=True, max_length=100)),
                ('DirectorName', models.CharField(blank=True, max_length=100)),
                ('MovieGenre', models.CharField(choices=[('Comedy', 'Comedy'), ('Romance', 'Romance'), ('Action', 'Action'), ('Drama', 'Drama'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Documentary', 'Documentary')], default='Action', max_length=20)),
                ('ReleaseYear', models.PositiveIntegerField()),
            ],
        ),
    ]
